version: "3.8"

services:
  postgres:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./gitignore/postgresql:/var/lib/postgresql/data
      - ./src/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
      - ./src/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./src/insert-table-records.sql:/docker-entrypoint-initdb.d/insert-table-records.sql
      - ./src/query-database.sql:/docker-entrypoint-initdb.d/query-database.sql

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
